
services:
  # 1. Database MySQL
  mysql-db:
    image: mysql:8.0
    container_name: share_account_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: share_account
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. Backend
  backend:
    build: 
      context: ./backend
    container_name: share_account_backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8080
      - MAIL_USER=${MAIL_USER}     
      - MAIL_PASS=${MAIL_PASS}
    depends_on:
      - mysql-db

  # 3. Frontend
  frontend:
    build: 
      context: ./frontend
    container_name: share_account_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

volumes:
  db_data: